backend:
  name: git-gateway
  branch: main
local_backend: true
media_folder: public/img
public_folder: /img
site_url: http://localhost:3000
logo_url: http://localhost:3000
locale: en
collections:
  - name: pages
    label: Pages
    format: json
    files:
      - label: Home
        name: home
        file: _content/home.json
        fields:
          - { label: Intro paragraph, name: introParagraph, widget: markdown }
          - label: Opening Hours
            name: openingHours
            widget: list
            fields:
              - { label: Service area, name: serviceArea, widget: string }
              - { label: Description, name: description, widget: string, required: false }
              - label: Schedules
                name: schedules
                widget: list
                fields:
                  - { label: Days, name: days, widget: string }
                  - { label: Opening times, name: openingTimes, widget: string }
          - { label: Our impact date range, name: ourImpactDates, widget: string }
          - label: Our impact stats
            name: ourImpactStats
            widget: list
            allow_add: true
            min: 3
            max: 3
            fields:
              - { label: Statistic value, name: statValue, widget: string }
              - { label: Statistic description, name: statDescription, widget: string }
          - label: Trustees
            name: trustees
            widget: list
            fields: 
              - { label: Name, name: name, widget: string }
  - name: content
    label: Content
    folder: _content/pages
    format: json
    create: true
    fields:
      - { label: Title, name: title, widget: string }
      - label: Paragraphs
        name: paragraphs
        widget: list
        fields:
          - { label: Heading, name: heading, widget: string, required: false }
          - { label: Content, name: content, widget: markdown }
          - { label: Include image, name: includeImage, widget: boolean, default: false }
          - label: "Featured Image"
            name: "featuredImage"
            widget: "image"
            required: false
            choose_url: false
          - { label: Image alt text, name: imageAlt, widget: string, required: false }
          - { label: Image on left, name: imageLeft, widget: boolean, default: true }
      - { label: Include in menu, name: includeMenu, widget: boolean, default: true }
      - { label: Include in footer, name: includeFooter, widget: boolean, default: false }